#!/bin/bash

MESSAGE="Outdated pre-release version"
VERSIONS=$*

PACKAGES="
@squarespace/template-engine
"
for version in $VERSIONS ; do
    for pkg in $PACKAGES ; do
        echo $pkg $version
        npm deprecate $pkg@$version "$MESSAGE"
    done
done


